# Generated by Django 2.1.3 on 2018-12-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=20)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CategoriaCliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Diarista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('valor', models.FloatField()),
                ('servicos', models.ManyToManyField(related_name='_servico_servicos_+', to='core.Servico')),
            ],
        ),
        migrations.AddField(
            model_name='diarista',
            name='servico',
            field=models.ManyToManyField(to='core.Servico'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='diarista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diarista'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funcionario'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='servico',
            field=models.ManyToManyField(to='core.Servico'),
        ),
    ]
