# Generated by Django 2.1.3 on 2018-12-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='servicos',
        ),
    ]
