# Generated by Django 2.1.3 on 2018-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servico_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='servico',
            field=models.ManyToManyField(related_name='_servico_servico_+', to='core.Servico'),
        ),
    ]
