# Generated by Django 2.1.3 on 2018-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181209_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboservico',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
