# Generated by Django 2.1.3 on 2018-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comboservico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacliente',
            name='desconto',
            field=models.FloatField(default=0),
        ),
    ]
