# Generated by Django 2.1.3 on 2018-12-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriacliente_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='servico',
            field=models.ManyToManyField(related_name='servicos', to='core.Servico'),
        ),
    ]
